@startuml

start
:用户输入生成数量;
repeat
    :激活码存放变量;
    while (循环16次)
        :随机生成一个整数;
        note right
            随机生成整数是为了实现如下概率
            数字概率 1/5 小写字母为 2/5 大写字母概率 2/5
        end note
        switch (随机整数)
        case (随机整数 == 0 或者 随机整数 == 1)
            :生成小写字母并添加到激活码存放变量中;
        case (随机整数 == 2 或者 随机整数 == 3) 
            :生成大写字母并添加到激活码存放变量中;
        case (随机整数 == 4)
            :生成数字并添加到激活码存放变量中;
        endswitch
    endwhile
    :添加生成的激活码到集合中;
repeat while (key 集合长度不等于用户输入生成数量)

stop

@enduml
